version: "3.3"

services:

  sandbox-pascal-abc:
    build:
      context: ..
      args:
        - SANDBOX_USER_UID=999
        - SANDBOX_DIR=/sandbox
      dockerfile: ./docker/Dockerfile
    container_name: sandbox-pascal-abc
    image: sandbox-pascal-abc
    volumes:
      - ../src:/app/src
      - import:/sandbox/import:ro
    ports:
      - "9005:9005"
    networks:
      - localhost
    environment:
      - DEBUG=true
      - SANDBOX_USER_UID=999
      - SANDBOX_DIR=/sandbox
    restart: on-failure
    command: gunicorn --pythonpath '/app/src' --bind 0:9005 app.main:app --reload -w 1

networks:
  localhost:
    external: true

volumes:
  import:
    external: true
